### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by prashnts** [devkhan/dkfs#1]
Guess which one I'll be copying. :3

**Comment by devkhan** [comment]
All right reserved by Devesh Khandelwal and Ankit Pathak till 21st April, 2016, thereafter, anyone can do WHATEVER THE :fu: THEY WANT TO DO.

Thanks for notifying though.

**Comment by prashnts** [comment]
_checks calendar_ Hmm. That means I can now, since it is 2016 already. :P 

<img width="693" alt="screen shot 2016-04-11 at 23 16 56" src="https://cloud.githubusercontent.com/assets/5663391/14436696/8436d0ce-003b-11e6-84f3-43c2b92270be.png">

**Comment by devkhan** [comment]
_oops, I made a mistake... So, what? It's my repo, I can edit others' responses._ :smiling_imp:

**Comment by devkhan** [comment]
Anyway, this goes on to show how we are stuck in time. :cry:

**Comment by prashnts** [comment]
Dude that was deep. :( @PragyaJaiswal

**Comment by devkhan** [comment]
Done. 55e26cec6b3f35aa70947e75eda116cb3d99cabe
